import { createContext, ReactNode, useContext, useState } from 'react';

export type Language = 'id' | 'ms' | 'en';

// Add supported currencies
export type Currency = 'IDR' | 'MYR' | 'USD';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  getTranslation: (key: string) => string;
  formatCurrency: (value: number) => string;
  currency: Currency;
  setCurrency: (currency: Currency) => void;
  convertToIDR: (value: number) => number;
  convertFromIDR: (value: number) => number;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Define the translation keys type
type TranslationKey = 
  | 'dashboard' | 'summary' | 'income' | 'expense' | 'netProfit' 
  | 'assets' | 'liabilities' | 'equity' | 'cashflowChart' 
  | 'logout' | 'changeLanguage' | 'indonesia' | 'malaysia' | 'english' | 'cancel'
  | 'asset' | 'liability'
  | 'currentAssets' | 'fixedAssets' | 'assetComposition'
  | 'errorLoadingData' | 'errorLoadingIncome' | 'errorLoadingExpense' | 'errorLoadingAsset' | 'errorLoadingLiability' | 'errorLoadingEquity'
  // Login/Register
  | 'loginTitle' | 'loginSubtitle' | 'email' | 'password' | 'showPassword' | 'hidePassword' | 'loginButton' | 'registerLink' | 'registerTitle' | 'registerSubtitle' | 'name' | 'confirmPassword' | 'role' | 'registerButton' | 'loginLink' | 'errorEmptyFields' | 'errorPasswordMismatch' | 'errorPasswordLength' | 'errorInvalidEmail' | 'successRegister' | 'errorLoginFailed' | 'errorRegisterFailed' | 'accountType' | 'entrepreneur' | 'accountant' | 'alreadyHaveAccount' | 'dontHaveAccount'
  | 'totalAssets'
  | 'netProfitTimeline' | 'startDate' | 'endDate' | 'currentNetProfit' | 'dataPoints' | 'noDataAvailable'
  | 'greetingMorning' | 'greetingAfternoon' | 'greetingEvening'
  | 'changeUp' | 'changeDown' | 'changeNoChange'
  | 'loadingChartData' | 'errorWithMessage'
  | 'filterByDate' | 'today' | 'week' | 'month' | 'quarter' | 'year'
  | 'startCustom' | 'endCustom'
  | 'monthlySummary' | 'totalNetProfit' | 'avgNetProfit' | 'totalIncome' | 'totalExpense'
  | 'noChartDataDetail' | 'assetLiabilitySummary'
  | 'addDataTitle' | 'formTitle' | 'saveButton' | 'successSave' | 'errorSave' | 'main' | 'side'
  | 'income' | 'expense' | 'asset' | 'liability' | 'equity'
  | 'salary' | 'utilities' | 'transport' | 'packaging' | 'advertising' | 'license' | 'rent' | 'others'
  | 'daily' | 'weekly' | 'monthly' | 'yearly'
  | 'unpaid' | 'partial' | 'paid'
  | 'initial' | 'retained' | 'withdrawal' | 'additional'
  | 'current' | 'fixed'
  | 'in_use' | 'damaged' | 'sold' | 'depreciated'
  | 'accountable' | 'monthly_loan' | 'repayment' | 'bank_loan'
  | 'selectCategory' | 'selectAssetCategory' | 'selectDate' | 'selectType' | 'selectStatus' | 'selectPeriod'
  | 'amount' | 'tax' | 'description' | 'optional' | 'name' | 'value' | 'category' | 'date' | 'dueDate' | 'status' | 'type' | 'assetName' | 'assetValue' | 'assetType' | 'assetCategory' | 'assetDate' | 'assetDescription' | 'liabilityName' | 'liabilityValue' | 'liabilityDate' | 'liabilityDueDate' | 'liabilityCategory' | 'paymentStatus' | 'equityName' | 'equityValue' | 'equityType' | 'equityDate' | 'equityDescription' | 'successTitle' | 'successMessage' | 'errorTitle' | 'errorMessage'
  | 'allTypes' | 'all' | 'searchNameOrDesc' | 'resetDateFilter' | 'grossProfit' | 'ebitda' | 'period' | 'confirmDelete' | 'delete' | 'successDelete' | 'errorDelete' | 'notFound' | 'noData' | 'lender'
  | 'changeCurrency' | 'currency' | 'indonesianRupiah' | 'malaysianRinggit' | 'usDollar'
  // New missing translations
  | 'building' | 'vehicle' | 'equipment' | 'machine' | 'fixed_investment' | 'cash_in_hand' | 'cash_in_bank' | 'receivable' | 'deposit' | 'inventory' | 'current_investment'
  | 'enterAmount' | 'enterTax' | 'enterDescription' | 'enterAssetName' | 'enterAssetValue' | 'enterAssetDescription' | 'enterLiabilityName' | 'enterLiabilityValue' | 'enterEquityName' | 'enterEquityValue' | 'enterEquityDescription'
  | 'editData' | 'saveChanges' | 'loading' | 'logoutConfirm'
  | 'accessDenied' | 'accessDeniedMessage' | 'goBack' | 'retry'
  | 'netCashFlow' | 'dataAggregated' | 'cashFlowSummary' | 'totalCashFlowIn' | 'totalCashFlowOut' | 'avgCashFlowIn' | 'avgCashFlowOut'
  | 'noChartData' | 'liabilityEquity'
  | 'profile' | 'editProfile' | 'changePassword' | 'currentPassword' | 'newPassword' | 'confirmNewPassword' | 'updateProfile' | 'profileUpdated' | 'passwordChanged' | 'nameRequired' | 'emailRequired' | 'allPasswordFieldsRequired' | 'passwordsDoNotMatch' | 'passwordMinLength' | 'failedToLoadProfile' | 'failedToUpdateProfile' | 'failedToChangePassword';

const translations: Record<Language, Record<TranslationKey, string>> = {
  id: {
    dashboard: 'Dasbor',
    summary: 'Ringkasan',
    income: 'Pendapatan',
    expense: 'Pengeluaran',
    netProfit: 'Untung Bersih',
    assets: 'Aset',
    liabilities: 'Liabiliti',
    equity: 'Ekuiti',
    cashflowChart: 'Grafik Aliran Tunai',
    netProfitTimeline: 'Timeline Untung Bersih',
    startDate: 'Tanggal Mulai',
    endDate: 'Tanggal Akhir',
    currentNetProfit: 'Untung Bersih Saat Ini',
    dataPoints: 'Data Points',
    noDataAvailable: 'Tidak ada data tersedia untuk rentang tanggal yang dipilih',
    logout: 'Keluar',
    changeLanguage: 'Ganti Bahasa',
    indonesia: 'Indonesia',
    malaysia: 'Malaysia',
    english: 'Inggris',
    cancel: 'Batal',
    asset: 'Aset',
    liability: 'Liabiliti',
    currentAssets: 'Aset Lancar',
    fixedAssets: 'Aset Tetap',
    assetComposition: 'Komposisi Aset',
    totalAssets: 'Total Aset',
    errorLoadingData: 'Gagal mengambil data dari server. Silakan coba lagi.',
    errorLoadingIncome: 'Gagal mengambil data pendapatan',
    errorLoadingExpense: 'Gagal mengambil data pengeluaran',
    errorLoadingAsset: 'Gagal mengambil data aset',
    errorLoadingLiability: 'Gagal mengambil data liabiliti',
    errorLoadingEquity: 'Gagal mengambil data ekuiti',
    // Login/Register
    loginTitle: 'Bookkeping',
    loginSubtitle: 'Masuk ke akun Anda',
    email: 'Email',
    password: 'Password',
    showPassword: 'Tampilkan Password',
    hidePassword: 'Sembunyikan Password',
    loginButton: 'Masuk',
    registerLink: 'Daftar',
    registerTitle: 'Bookkeping',
    registerSubtitle: 'Buat akun baru',
    name: 'Nama Lengkap',
    confirmPassword: 'Konfirmasi Password',
    role: 'Jenis Akun',
    registerButton: 'Daftar',
    loginLink: 'Masuk',
    errorEmptyFields: 'Semua field harus diisi',
    errorPasswordMismatch: 'Password dan konfirmasi password harus sama',
    errorPasswordLength: 'Password minimal 6 karakter',
    errorInvalidEmail: 'Format email tidak valid',
    successRegister: 'Registrasi berhasil',
    errorLoginFailed: 'Login gagal',
    errorRegisterFailed: 'Registrasi gagal',
    accountType: 'Jenis Akun',
    entrepreneur: 'Usahawan',
    accountant: 'Akuntan',
    alreadyHaveAccount: 'Sudah punya akun?',
    dontHaveAccount: 'Belum punya akun?',
    greetingMorning: 'Selamat pagi',
    greetingAfternoon: 'Selamat siang',
    greetingEvening: 'Selamat malam',
    changeUp: 'Naik {x}% dari bulan lalu',
    changeDown: 'Turun {x}% dari bulan lalu',
    changeNoChange: 'Tidak ada perubahan dari bulan lalu',
    loadingChartData: 'Memuat data grafik...',
    errorWithMessage: 'Error: {msg}',
    filterByDate: 'Filter Tanggal',
    today: 'Hari Ini',
    week: '7 Hari',
    month: 'Bulan Ini',
    quarter: '3 Bulan',
    year: 'Tahun Ini',
    startCustom: 'Mulai',
    endCustom: 'Akhir',
    monthlySummary: 'Ringkasan Bulanan',
    totalNetProfit: 'Total Untung Bersih',
    avgNetProfit: 'Rata-rata Harian',
    totalIncome: 'Total Pendapatan',
    totalExpense: 'Total Pengeluaran',
    noChartDataDetail: 'Belum ada data aset, liabilitas, atau ekuitas yang bisa ditampilkan.',
    assetLiabilitySummary: 'Ringkasan Aset dan Kewajiban',
    addDataTitle: 'Tambah Data',
    formTitle: 'Form',
    saveButton: 'Simpan',
    successSave: 'Data berhasil disimpan!',
    errorSave: 'Gagal menyimpan data. Silakan coba lagi.',
    salary: 'Gaji',
    utilities: 'Bil Utiliti',
    transport: 'Minyak/Pengangkutan',
    packaging: 'Kos Pembungkusan',
    advertising: 'Iklan',
    license: 'Yuran Lesen',
    rent: 'Sewa',
    others: 'Lain-lain',
    daily: 'Harian',
    weekly: 'Mingguan',
    monthly: 'Bulanan',
    yearly: 'Tahunan',
    unpaid: 'Belum Dibayar',
    partial: 'Sebagian',
    paid: 'Lunas',
    initial: 'Modal Awal / Modal Disetor',
    retained: 'Laba Ditahan',
    withdrawal: 'Prive',
    additional: 'Tambahan Modal Disetor',
    current: 'Aset Lancar',
    fixed: 'Aset Tetap',
    in_use: 'Masih Digunakan',
    damaged: 'Rusak',
    sold: 'Dijual',
    depreciated: 'Disusutkan',
    accountable: 'Utang Usaha',
    monthly_loan: 'Pinjaman Bulanan',
    repayment: 'Pembayaran Kembali',
    bank_loan: 'Pinjaman Bank',
    selectCategory: 'Pilih kategori',
    selectAssetCategory: 'Pilih kategori aset',
    selectDate: 'Pilih tanggal',
    selectType: 'Pilih tipe',
    selectStatus: 'Pilih status',
    selectPeriod: 'Pilih periode',
    amount: 'Jumlah Uang',
    tax: 'Pajak (%)',
    description: 'Keterangan',
    optional: '(opsional)',
    category: 'Kategori',
    date: 'Tanggal',
    dueDate: 'Jatuh Tempo',
    status: 'Status',
    type: 'Tipe',
    assetName: 'Nama Aset',
    assetValue: 'Nilai Aset',
    assetType: 'Jenis Aset',
    assetCategory: 'Kategori Aset',
    assetDate: 'Tanggal Perolehan',
    assetDescription: 'Keterangan tentang aset',
    liabilityName: 'Nama Liabilitas',
    liabilityValue: 'Nilai Liabilitas',
    liabilityDate: 'Tanggal Pencatatan',
    liabilityDueDate: 'Jatuh Tempo',
    liabilityCategory: 'Kategori Liabilitas',
    paymentStatus: 'Status Pembayaran',
    equityName: 'Nama Ekuiti',
    equityValue: 'Nilai Ekuiti',
    equityType: 'Jenis Ekuiti',
    equityDate: 'Tanggal Transaksi',
    equityDescription: 'Keterangan tentang ekuiti',
    successTitle: 'Berhasil',
    successMessage: 'Data berhasil disimpan!',
    errorTitle: 'Error',
    errorMessage: 'Gagal menyimpan data. Silakan coba lagi.',
    allTypes: 'Semua Tipe',
    all: 'Semua',
    searchNameOrDesc: 'Cari nama atau deskripsi... ',
    resetDateFilter: 'Reset Filter Tanggal',
    grossProfit: 'Laba Kotor',
    ebitda: 'EBITDA',
    period: 'Periode',
    confirmDelete: 'Konfirmasi Hapus',
    delete: 'Hapus',
    successDelete: 'Data berhasil dihapus',
    errorDelete: 'Gagal menghapus data. Silakan coba lagi.',
    notFound: 'Data tidak ditemukan',
    noData: 'Tidak ada data',
    lender: 'Pemberi',
    main: 'Utama',
    side: 'Tambahan',
    value: 'Nilai',
    changeCurrency: 'Ganti Mata Uang',
    currency: 'Mata Uang',
    indonesianRupiah: 'Rupiah Indonesia',
    malaysianRinggit: 'Ringgit Malaysia',
    usDollar: 'Dolar Amerika',
    // New missing translations
    building: 'Bangunan',
    vehicle: 'Kendaraan',
    equipment: 'Peralatan',
    machine: 'Mesin',
    fixed_investment: 'Investasi Tetap',
    cash_in_hand: 'Kas di Tangan',
    cash_in_bank: 'Kas di Bank',
    receivable: 'Piutang',
    deposit: 'Deposit',
    inventory: 'Persediaan',
    current_investment: 'Investasi Lancar',
    enterAmount: 'Masukkan jumlah',
    enterTax: 'Masukkan pajak',
    enterDescription: 'Masukkan keterangan',
    enterAssetName: 'Masukkan nama aset',
    enterAssetValue: 'Masukkan nilai aset',
    enterAssetDescription: 'Masukkan keterangan aset',
    enterLiabilityName: 'Masukkan nama liabilitas',
    enterLiabilityValue: 'Masukkan nilai liabilitas',
    enterEquityName: 'Masukkan nama ekuiti',
    enterEquityValue: 'Masukkan nilai ekuiti',
    enterEquityDescription: 'Masukkan keterangan ekuiti',
    editData: 'Edit Data',
    saveChanges: 'Simpan Perubahan',
    loading: 'Memuat...',
    logoutConfirm: 'Apakah Anda yakin ingin keluar?',
    accessDenied: 'Akses Ditolak',
    accessDeniedMessage: 'Anda tidak memiliki izin untuk mengakses halaman ini. Hanya akuntan yang dapat melihat laporan keuangan.',
    goBack: 'Kembali',
    retry: 'Coba Lagi',
    netCashFlow: 'Aliran Kas Bersih',
    dataAggregated: 'Data Dikelompokkan',
    cashFlowSummary: 'Ringkasan Aliran Kas',
    totalCashFlowIn: 'Total Kas Masuk',
    totalCashFlowOut: 'Total Kas Keluar',
    avgCashFlowIn: 'Rata-rata Kas Masuk',
    avgCashFlowOut: 'Rata-rata Kas Keluar',
    noChartData: 'Tidak Ada Data Grafik',
    liabilityEquity: 'Liabilitas & Ekuiti',
    profile: 'Profil',
    editProfile: 'Edit Profil',
    changePassword: 'Ubah Password',
    currentPassword: 'Password Saat Ini',
    newPassword: 'Password Baru',
    confirmNewPassword: 'Konfirmasi Password Baru',
    updateProfile: 'Perbarui Profil',
    profileUpdated: 'Profil berhasil diperbarui',
    passwordChanged: 'Password berhasil diubah',
    nameRequired: 'Nama dan email wajib diisi',
    emailRequired: 'Nama dan email wajib diisi',
    allPasswordFieldsRequired: 'Semua field password wajib diisi',
    passwordsDoNotMatch: 'Password baru tidak cocok',
    passwordMinLength: 'Password baru minimal 6 karakter',
    failedToLoadProfile: 'Gagal memuat profil',
    failedToUpdateProfile: 'Gagal memperbarui profil',
    failedToChangePassword: 'Gagal mengubah password',
  },
  ms: {
    dashboard: 'Papan Pemuka',
    summary: 'Ringkasan',
    income: 'Pendapatan',
    expense: 'Perbelanjaan',
    netProfit: 'Untung Bersih',
    assets: 'Aset',
    liabilities: 'Liabiliti',
    equity: 'Ekuiti',
    cashflowChart: 'Carta Aliran Tunai',
    netProfitTimeline: 'Timeline Untung Bersih',
    startDate: 'Tanggal Mulai',
    endDate: 'Tanggal Akhir',
    currentNetProfit: 'Untung Bersih Saat Ini',
    dataPoints: 'Data Points',
    noDataAvailable: 'Tidak ada data tersedia untuk rentang tanggal yang dipilih',
    logout: 'Log Keluar',
    changeLanguage: 'Tukar Bahasa',
    indonesia: 'Indonesia',
    malaysia: 'Malaysia',
    english: 'Inggeris',
    cancel: 'Batal',
    asset: 'Aset',
    liability: 'Liabiliti',
    currentAssets: 'Aset Semasa',
    fixedAssets: 'Aset Tetap',
    assetComposition: 'Komposisi Aset',
    totalAssets: 'Jumlah Aset',
    errorLoadingData: 'Gagal mengambil data dari server. Sila cuba lagi.',
    errorLoadingIncome: 'Gagal mengambil data pendapatan',
    errorLoadingExpense: 'Gagal mengambil data perbelanjaan',
    errorLoadingAsset: 'Gagal mengambil data aset',
    errorLoadingLiability: 'Gagal mengambil data liabiliti',
    errorLoadingEquity: 'Gagal mengambil data ekuiti',
    // Login/Register
    loginTitle: 'Bookkeping',
    loginSubtitle: 'Log masuk ke akaun anda',
    email: 'Emel',
    password: 'Kata Laluan',
    showPassword: 'Tunjuk Kata Laluan',
    hidePassword: 'Sembunyi Kata Laluan',
    loginButton: 'Log Masuk',
    registerLink: 'Daftar',
    registerTitle: 'Bookkeping',
    registerSubtitle: 'Buat akaun baru',
    name: 'Nama Penuh',
    confirmPassword: 'Sahkan Kata Laluan',
    role: 'Jenis Akaun',
    registerButton: 'Daftar',
    loginLink: 'Log Masuk',
    errorEmptyFields: 'Semua medan mesti diisi',
    errorPasswordMismatch: 'Kata laluan dan pengesahan mesti sama',
    errorPasswordLength: 'Kata laluan minimum 6 aksara',
    errorInvalidEmail: 'Format emel tidak sah',
    successRegister: 'Pendaftaran berjaya',
    errorLoginFailed: 'Log masuk gagal',
    errorRegisterFailed: 'Pendaftaran gagal',
    accountType: 'Jenis Akaun',
    entrepreneur: 'Usahawan',
    accountant: 'Akauntan',
    alreadyHaveAccount: 'Sudah ada akaun?',
    dontHaveAccount: 'Belum ada akaun?',
    greetingMorning: 'Selamat pagi',
    greetingAfternoon: 'Selamat tengah hari',
    greetingEvening: 'Selamat malam',
    changeUp: 'Naik {x}% dari bulan lepas',
    changeDown: 'Turun {x}% dari bulan lepas',
    changeNoChange: 'Tiada perubahan dari bulan lepas',
    loadingChartData: 'Memuat data carta...',
    errorWithMessage: 'Ralat: {msg}',
    filterByDate: 'Tapis Tarikh',
    today: 'Hari Ini',
    week: '7 Hari',
    month: 'Bulan Ini',
    quarter: '3 Bulan',
    year: 'Tahun Ini',
    startCustom: 'Mula',
    endCustom: 'Akhir',
    monthlySummary: 'Ringkasan Bulanan',
    totalNetProfit: 'Jumlah Untung Bersih',
    avgNetProfit: 'Purata Harian',
    totalIncome: 'Jumlah Pendapatan',
    totalExpense: 'Jumlah Perbelanjaan',
    noChartDataDetail: 'Belum ada data aset, liabiliti, atau ekuiti yang boleh dipaparkan.',
    assetLiabilitySummary: 'Ringkasan Aset dan Liabiliti',
    addDataTitle: 'Tambah Data',
    formTitle: 'Borang',
    saveButton: 'Simpan',
    successSave: 'Data berjaya disimpan!',
    errorSave: 'Gagal menyimpan data. Sila cuba lagi.',
    salary: 'Gaji',
    utilities: 'Bil Utiliti',
    transport: 'Minyak/Pengangkutan',
    packaging: 'Kos Pembungkusan',
    advertising: 'Iklan',
    license: 'Yuran Lesen',
    rent: 'Sewa',
    others: 'Lain-lain',
    daily: 'Harian',
    weekly: 'Mingguan',
    monthly: 'Bulanan',
    yearly: 'Tahunan',
    unpaid: 'Belum Dibayar',
    partial: 'Sebahagian',
    paid: 'Lunas',
    initial: 'Modal Awal / Modal Disetor',
    retained: 'Keuntungan Ditahan',
    withdrawal: 'Prive',
    additional: 'Tambahan Modal Disetor',
    current: 'Aset Semasa',
    fixed: 'Aset Tetap',
    in_use: 'Masih Digunakan',
    damaged: 'Rosak',
    sold: 'Dijual',
    depreciated: 'Disusutkan',
    accountable: 'Hutang Usaha',
    monthly_loan: 'Pinjaman Bulanan',
    repayment: 'Bayaran Balik',
    bank_loan: 'Pinjaman Bank',
    selectCategory: 'Pilih kategori',
    selectAssetCategory: 'Pilih kategori aset',
    selectDate: 'Pilih tarikh',
    selectType: 'Pilih jenis',
    selectStatus: 'Pilih status',
    selectPeriod: 'Pilih tempoh',
    amount: 'Jumlah Wang',
    tax: 'Cukai (%)',
    description: 'Keterangan',
    optional: '(opsyenal)',
    category: 'Kategori',
    date: 'Tarikh',
    dueDate: 'Tarikh Tamat',
    status: 'Status',
    type: 'Jenis',
    assetName: 'Nama Aset',
    assetValue: 'Nilai Aset',
    assetType: 'Jenis Aset',
    assetCategory: 'Kategori Aset',
    assetDate: 'Tarikh Perolehan',
    assetDescription: 'Keterangan tentang aset',
    liabilityName: 'Nama Liabiliti',
    liabilityValue: 'Nilai Liabiliti',
    liabilityDate: 'Tarikh Catatan',
    liabilityDueDate: 'Tarikh Tamat',
    liabilityCategory: 'Kategori Liabiliti',
    paymentStatus: 'Status Pembayaran',
    equityName: 'Nama Ekuiti',
    equityValue: 'Nilai Ekuiti',
    equityType: 'Jenis Ekuiti',
    equityDate: 'Tarikh Transaksi',
    equityDescription: 'Keterangan tentang ekuiti',
    successTitle: 'Berjaya',
    successMessage: 'Data berjaya disimpan!',
    errorTitle: 'Ralat',
    errorMessage: 'Gagal menyimpan data. Sila cuba lagi.',
    allTypes: 'Semua Jenis',
    all: 'Semua',
    searchNameOrDesc: 'Cari nama atau keterangan... ',
    resetDateFilter: 'Reset Tapis Tarikh',
    grossProfit: 'Untung Kasar',
    ebitda: 'EBITDA',
    period: 'Tempoh',
    confirmDelete: 'Sahkan Padam',
    delete: 'Padam',
    successDelete: 'Data berjaya dipadam',
    errorDelete: 'Gagal memadam data. Sila cuba lagi.',
    notFound: 'Data tidak dijumpai',
    noData: 'Tiada data',
    lender: 'Pemberi',
    main: 'Utama',
    side: 'Tambahan',
    value: 'Nilai',
    changeCurrency: 'Tukar Mata Wang',
    currency: 'Mata Wang',
    indonesianRupiah: 'Rupiah Indonesia',
    malaysianRinggit: 'Ringgit Malaysia',
    usDollar: 'Dolar Amerika',
    // New missing translations
    building: 'Bangunan',
    vehicle: 'Kenderaan',
    equipment: 'Peralatan',
    machine: 'Mesin',
    fixed_investment: 'Pelaburan Tetap',
    cash_in_hand: 'Tunai di Tangan',
    cash_in_bank: 'Tunai di Bank',
    receivable: 'Hutang',
    deposit: 'Deposit',
    inventory: 'Inventori',
    current_investment: 'Pelaburan Semasa',
    enterAmount: 'Masukkan jumlah',
    enterTax: 'Masukkan cukai',
    enterDescription: 'Masukkan keterangan',
    enterAssetName: 'Masukkan nama aset',
    enterAssetValue: 'Masukkan nilai aset',
    enterAssetDescription: 'Masukkan keterangan aset',
    enterLiabilityName: 'Masukkan nama liabiliti',
    enterLiabilityValue: 'Masukkan nilai liabiliti',
    enterEquityName: 'Masukkan nama ekuiti',
    enterEquityValue: 'Masukkan nilai ekuiti',
    enterEquityDescription: 'Masukkan keterangan ekuiti',
    editData: 'Edit Data',
    saveChanges: 'Simpan Perubahan',
    loading: 'Memuat...',
    logoutConfirm: 'Adakah anda pasti mahu log keluar?',
    accessDenied: 'Akses Ditolak',
    accessDeniedMessage: 'Anda tidak mempunyai kebenaran untuk mengakses halaman ini. Hanya akauntan yang boleh melihat laporan kewangan.',
    goBack: 'Kembali',
    retry: 'Cuba Lagi',
    netCashFlow: 'Aliran Tunai Bersih',
    dataAggregated: 'Data Dikumpulkan',
    cashFlowSummary: 'Ringkasan Aliran Tunai',
    totalCashFlowIn: 'Jumlah Tunai Masuk',
    totalCashFlowOut: 'Jumlah Tunai Keluar',
    avgCashFlowIn: 'Purata Tunai Masuk',
    avgCashFlowOut: 'Purata Tunai Keluar',
    noChartData: 'Tiada Data Carta',
    liabilityEquity: 'Liabiliti & Ekuiti',
    profile: 'Profil',
    editProfile: 'Edit Profil',
    changePassword: 'Tukar Kata Laluan',
    currentPassword: 'Kata Laluan Semasa',
    newPassword: 'Kata Laluan Baru',
    confirmNewPassword: 'Sahkan Kata Laluan Baru',
    updateProfile: 'Kemas Kini Profil',
    profileUpdated: 'Profil berjaya dikemas kini',
    passwordChanged: 'Kata laluan berjaya ditukar',
    nameRequired: 'Nama dan emel diperlukan',
    emailRequired: 'Nama dan emel diperlukan',
    allPasswordFieldsRequired: 'Semua medan kata laluan diperlukan',
    passwordsDoNotMatch: 'Kata laluan baru tidak sepadan',
    passwordMinLength: 'Kata laluan baru minimum 6 aksara',
    failedToLoadProfile: 'Gagal memuat profil',
    failedToUpdateProfile: 'Gagal mengemas kini profil',
    failedToChangePassword: 'Gagal menukar kata laluan',
  },
  en: {
    dashboard: 'Dashboard',
    summary: 'Summary',
    income: 'Income',
    expense: 'Expense',
    netProfit: 'Net Profit',
    assets: 'Assets',
    liabilities: 'Liabilities',
    equity: 'Equity',
    cashflowChart: 'Cashflow Chart',
    netProfitTimeline: 'Net Profit Timeline',
    startDate: 'Start Date',
    endDate: 'End Date',
    currentNetProfit: 'Current Net Profit',
    dataPoints: 'Data Points',
    noDataAvailable: 'No data available for the selected date range',
    logout: 'Logout',
    changeLanguage: 'Change Language',
    indonesia: 'Indonesian',
    malaysia: 'Malaysian',
    english: 'English',
    cancel: 'Cancel',
    asset: 'Asset',
    liability: 'Liability',
    currentAssets: 'Current Assets',
    fixedAssets: 'Fixed Assets',
    assetComposition: 'Asset Composition',
    totalAssets: 'Total Assets',
    errorLoadingData: 'Failed to load data from server. Please try again.',
    errorLoadingIncome: 'Failed to load income data',
    errorLoadingExpense: 'Failed to load expense data',
    errorLoadingAsset: 'Failed to load asset data',
    errorLoadingLiability: 'Failed to load liability data',
    errorLoadingEquity: 'Failed to load equity data',
    // Login/Register
    loginTitle: 'Bookkeping',
    loginSubtitle: 'Sign in to your account',
    email: 'Email',
    password: 'Password',
    showPassword: 'Show Password',
    hidePassword: 'Hide Password',
    loginButton: 'Login',
    registerLink: 'Register',
    registerTitle: 'Bookkeping',
    registerSubtitle: 'Create a new account',
    name: 'Full Name',
    confirmPassword: 'Confirm Password',
    role: 'Account Type',
    registerButton: 'Register',
    loginLink: 'Login',
    errorEmptyFields: 'All fields are required',
    errorPasswordMismatch: 'Password and confirmation must match',
    errorPasswordLength: 'Password must be at least 6 characters',
    errorInvalidEmail: 'Invalid email format',
    successRegister: 'Registration successful',
    errorLoginFailed: 'Login failed',
    errorRegisterFailed: 'Registration failed',
    accountType: 'Account Type',
    entrepreneur: 'Entrepreneur',
    accountant: 'Accountant',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: 'Don\'t have an account?',
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    changeUp: 'Up {x}% from last month',
    changeDown: 'Down {x}% from last month',
    changeNoChange: 'No change from last month',
    loadingChartData: 'Loading chart data...',
    errorWithMessage: 'Error: {msg}',
    filterByDate: 'Filter By Date',
    today: 'Today',
    week: '7 Days',
    month: 'This Month',
    quarter: '3 Months',
    year: 'This Year',
    startCustom: 'Start',
    endCustom: 'End',
    monthlySummary: 'Monthly Summary',
    totalNetProfit: 'Total Net Profit',
    avgNetProfit: 'Daily Average',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    noChartDataDetail: 'No asset, liability, or equity data to display yet.',
    assetLiabilitySummary: 'Asset and Liability Summary',
    addDataTitle: 'Add Data',
    formTitle: 'Form',
    saveButton: 'Save',
    successSave: 'Data saved successfully!',
    errorSave: 'Failed to save data. Please try again.',
    salary: 'Salary',
    utilities: 'Utilities',
    transport: 'Transport',
    packaging: 'Packaging',
    advertising: 'Advertising',
    license: 'License',
    rent: 'Rent',
    others: 'Others',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    unpaid: 'Unpaid',
    partial: 'Partial',
    paid: 'Paid',
    initial: 'Initial Capital / Paid-in Capital',
    retained: 'Retained Earnings',
    withdrawal: 'Withdrawal',
    additional: 'Additional Paid-in Capital',
    current: 'Current Asset',
    fixed: 'Fixed Asset',
    in_use: 'In Use',
    damaged: 'Damaged',
    sold: 'Sold',
    depreciated: 'Depreciated',
    accountable: 'Accountable Debt',
    monthly_loan: 'Monthly Loan',
    repayment: 'Repayment',
    bank_loan: 'Bank Loan',
    selectCategory: 'Select category',
    selectAssetCategory: 'Select asset category',
    selectDate: 'Select date',
    selectType: 'Select type',
    selectStatus: 'Select status',
    selectPeriod: 'Select period',
    amount: 'Amount',
    tax: 'Tax (%)',
    description: 'Description',
    optional: '(optional)',
    category: 'Category',
    date: 'Date',
    dueDate: 'Due Date',
    status: 'Status',
    type: 'Type',
    assetName: 'Asset Name',
    assetValue: 'Asset Value',
    assetType: 'Asset Type',
    assetCategory: 'Asset Category',
    assetDate: 'Acquisition Date',
    assetDescription: 'Asset Description',
    liabilityName: 'Liability Name',
    liabilityValue: 'Liability Value',
    liabilityDate: 'Record Date',
    liabilityDueDate: 'Due Date',
    liabilityCategory: 'Liability Category',
    paymentStatus: 'Payment Status',
    equityName: 'Equity Name',
    equityValue: 'Equity Value',
    equityType: 'Equity Type',
    equityDate: 'Transaction Date',
    equityDescription: 'Equity Description',
    successTitle: 'Success',
    successMessage: 'Data saved successfully!',
    errorTitle: 'Error',
    errorMessage: 'Failed to save data. Please try again.',
    allTypes: 'All Types',
    all: 'All',
    searchNameOrDesc: 'Search name or description... ',
    resetDateFilter: 'Reset Date Filter',
    grossProfit: 'Gross Profit',
    ebitda: 'EBITDA',
    period: 'Period',
    confirmDelete: 'Confirm Delete',
    delete: 'Delete',
    successDelete: 'Data deleted successfully',
    errorDelete: 'Failed to delete data. Please try again.',
    notFound: 'Data not found',
    noData: 'No data',
    lender: 'Lender',
    main: 'Main',
    side: 'Additional',
    value: 'Value',
    changeCurrency: 'Change Currency',
    currency: 'Currency',
    indonesianRupiah: 'Indonesian Rupiah',
    malaysianRinggit: 'Malaysian Ringgit',
    usDollar: 'US Dollar',
    // New missing translations
    building: 'Building',
    vehicle: 'Vehicle',
    equipment: 'Equipment',
    machine: 'Machine',
    fixed_investment: 'Fixed Investment',
    cash_in_hand: 'Cash in Hand',
    cash_in_bank: 'Cash in Bank',
    receivable: 'Receivable',
    deposit: 'Deposit',
    inventory: 'Inventory',
    current_investment: 'Current Investment',
    enterAmount: 'Enter amount',
    enterTax: 'Enter tax',
    enterDescription: 'Enter description',
    enterAssetName: 'Enter asset name',
    enterAssetValue: 'Enter asset value',
    enterAssetDescription: 'Enter asset description',
    enterLiabilityName: 'Enter liability name',
    enterLiabilityValue: 'Enter liability value',
    enterEquityName: 'Enter equity name',
    enterEquityValue: 'Enter equity value',
    enterEquityDescription: 'Enter equity description',
    editData: 'Edit Data',
    saveChanges: 'Save Changes',
    loading: 'Loading...',
    logoutConfirm: 'Are you sure you want to logout?',
    accessDenied: 'Access Denied',
    accessDeniedMessage: 'You do not have permission to access this page. Only accountants can view financial reports.',
    goBack: 'Go Back',
    retry: 'Retry',
    netCashFlow: 'Net Cash Flow',
    dataAggregated: 'Data Aggregated',
    cashFlowSummary: 'Cash Flow Summary',
    totalCashFlowIn: 'Total Cash In',
    totalCashFlowOut: 'Total Cash Out',
    avgCashFlowIn: 'Avg Cash In',
    avgCashFlowOut: 'Avg Cash Out',
    noChartData: 'No Chart Data',
    liabilityEquity: 'Liabilities & Equity',
    profile: 'Profile',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updateProfile: 'Update Profile',
    profileUpdated: 'Profile updated successfully',
    passwordChanged: 'Password changed successfully',
    nameRequired: 'Name and email are required',
    emailRequired: 'Name and email are required',
    allPasswordFieldsRequired: 'All password fields are required',
    passwordsDoNotMatch: 'New passwords do not match',
    passwordMinLength: 'New password must be at least 6 characters',
    failedToLoadProfile: 'Failed to load profile',
    failedToUpdateProfile: 'Failed to update profile',
    failedToChangePassword: 'Failed to change password',
  }
};




let currencyRates: { [key in Currency]: number } = {
  IDR: 1,
  MYR: 0.0003,
  USD: 0.000065,
};

async function fetchExchangeRates() {
  try {
    const res = await fetch('https://open.er-api.com/v6/latest/IDR'); // GRATIS TANPA API KEY
    const data = await res.json();
    if (data && data.rates) {
      currencyRates = {
        IDR: 1,
        MYR: data.rates.MYR,
        USD: data.rates.USD,
      };
    }
  } catch (err) {
    console.error('Failed to fetch exchange rates:', err);
  }
}

fetchExchangeRates();

const currencyFormatters: { [key in Currency]: (valueInIDR: number) => string } = {
  IDR: (valueInIDR) =>
    `Rp ${valueInIDR.toLocaleString('id-ID', { maximumFractionDigits: 2 })}`,
  MYR: (valueInIDR) => {
    const converted = valueInIDR * currencyRates.MYR;
    return `RM ${converted.toLocaleString('en-MY', { maximumFractionDigits: 2 })}`;
  },
  USD: (valueInIDR) => {
    const converted = valueInIDR * currencyRates.USD;
    return `$${converted.toLocaleString('en-US', { maximumFractionDigits: 2 })}`;
  },
};


export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('id');
  const [currency, setCurrency] = useState<Currency>('IDR');

  const getTranslation = (key: string): string => {
    return translations[language][key as TranslationKey] || key;
  };

  const formatCurrency = (value: number) => {
    return currencyFormatters[currency](value);
  };

  const convertToIDR = (value: number) => {
    // Convert from current currency to IDR
    if (currency === 'IDR') return value;
    if (currency === 'MYR') return value / currencyRates.MYR;
    if (currency === 'USD') return value / currencyRates.USD;
    return value;
  };

  const convertFromIDR = (value: number) => {
    // Convert from IDR to current currency
    if (currency === 'IDR') return value;
    if (currency === 'MYR') return value * currencyRates.MYR;
    if (currency === 'USD') return value * currencyRates.USD;
    return value;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      getTranslation, 
      formatCurrency, 
      currency, 
      setCurrency,
      convertToIDR,
      convertFromIDR
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 